name: TP2-ES2-TESTS

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install g++ -y
        elif [[ $RUNNER_OS == "macOS" ]]; then
          brew install gcc
        elif [[ $RUNNER_OS == "Windows" ]]; then
          choco install mingw
        fi

    - name: Compile and Run Tests
      shell: bash
      run: |
        mkdir obj
        mkdir bin
        if [[ $RUNNER_OS == "Windows" ]]; then
          g++ src/map.cpp tests/testRunner.cpp -o bin/testRunner.exe -Wall -Iinclude -Og -g -std=c++11 -lm
          ./bin/testRunner.exe
        else
          g++ src/map.cpp tests/testRunner.cpp -o bin/testRunner -Wall -Iinclude -Og -g -std=c++11 -lm
          ./bin/testRunner
        fi