name: TP2-ES2-TESTS

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install g++ -y
        elif [[ $RUNNER_OS == "macOS" ]]; then
          brew install gcc
        elif [[ $RUNNER_OS == "Windows" ]]; then
          choco install mingw
        fi

    - name: Compile and Run Tests
      shell: bash
      run: |
        mkdir obj
        mkdir bin
        make
        ./bin/testRunner tests/teste1.in test/teste2.in test/teste3.in test/teste4.in test/teste5.in