name: TP2-ES2-TESTS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Compile and Run Tests
      shell: bash
      run: |
        mkdir obj
        mkdir bin
        make
        if [[ $RUNNER_OS == "Windows" ]]; then
          cd bin
          dir
          g++ -o bin/testRunner.exe -Wall -Iinclude -Og -g -std=c++11 tests/testRunner.cpp src/map.cpp -lm
          dir
          ./testRunner.exe ../tests/teste1.in
        fi
        ./bin/testRunner tests/teste1.in