
name: TP2-ES2-TESTS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Compile and Run Tests
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Windows" ]]; then
          g++ src/map.cpp tests/testRunner.cpp -o testRunner.exe
          ./testRunner.exe tests/teste1.in
        else
          g++ src/map.cpp tests/testRunner.cpp -o testRunner
          ./testRunner tests/teste1.in
        fi
      
