name: TP2-ES2-TESTS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Compile and Run Tests
      shell: bash
      run: |
        mkdir obj
        mkdir bin
        make
        if [[ $RUNNER_OS == "Windows" ]]; then
          dir
          cd bin
          dir
          cd ..
          cd tests
          dir
          cd ..
        else
          ls
        fi
        ./bin/testRunner tests/teste1.in