name: TP2-ES2-TESTS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Compile and Run Tests
      shell: bash
      run: |
        mkdir obj
        mkdir bin
        if [[ $RUNNER_OS == "Windows" ]]; then
          g++ src/map.cpp tests/testRunner.cpp -o bin/testRunner.exe -Wall -Iinclude -Og -g -std=c++11 -lm
          ./bin/testRunner.exe tests/teste1.in
        else
          make
          ./bin/testRunner tests/teste1.in
        fi