name: TP2-ES2-TESTS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install g++ -y
        elif [[ $RUNNER_OS == "macOS" ]]; then
          brew install gcc
        elif [[ $RUNNER_OS == "Windows" ]]; then
          choco install mingw
        fi

    - name: Compile and Run Tests
      shell: bash
      run: |
        mkdir obj
        mkdir bin
        if [[ $RUNNER_OS == "Windows" ]]; then
          g++ -o bin/testRunner.exe -Wall -Iinclude -Og -g -std=c++11 tests/testRunner.cpp src/map.cpp -lm 
          ./bin/testRunner.exe tests/teste1.in
        else
          make
          ./bin/testRunner tests/teste1.in
        fi